import { ScrollView, StyleSheet, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { AppText } from "@/src/components/common/AppText";
import { ExpenseRow } from "@/src/components/common/ExpenseRow";
import { QuickAction } from "@/src/components/common/QuickAction";
import { useHomeData } from "@/src/hooks/useHomeData";
import { brand } from "@/src/config/brand";
import { colors, radius, spacing } from "@/src/theme/tokens";

export default function HomeScreen() {
  const { summary, expenses, loading } = useHomeData();
  return <SafeAreaView style={styles.safe} edges={["top"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><AppText variant="caption" style={{ color: colors.textMuted }}>Good morning 👋</AppText><AppText variant="title">{brand.name}</AppText></View><View style={styles.avatar}><AppText variant="bodyMedium">DS</AppText></View></View>
    <View style={styles.summaryCard}><View style={styles.month}><AppText variant="caption" style={{ color: colors.textMuted }}>{summary?.monthLabel ?? "September"}</AppText><Ionicons name="chevron-down" size={16} color={colors.textMuted} /></View><AppText variant="amount">₹{(summary?.totalSpent ?? 0).toLocaleString("en-IN")}</AppText><AppText variant="caption" style={{ color: colors.textMuted }}>total spent this month</AppText><View style={styles.balanceRow}><View><AppText variant="caption" style={{ color: colors.textMuted }}>You owe</AppText><AppText variant="bodyMedium">₹{summary?.youOwe ?? 0}</AppText></View><View><AppText variant="caption" style={{ color: colors.textMuted }}>Owed to you</AppText><AppText variant="bodyMedium" style={{ color: colors.success }}>₹{summary?.owedToYou ?? 0}</AppText></View></View></View>
    <AppText variant="h2" style={styles.sectionTitle}>Quick actions</AppText><View style={styles.actions}>{[["Scan","qr-code"],["Split","git-branch-outline"],["Request","arrow-down-circle-outline"],["Expense","add-circle-outline"]].map(([label, icon]) => <QuickAction key={label} label={label} icon={icon as keyof typeof Ionicons.glyphMap} />)}</View>
    <View style={styles.sectionHeader}><AppText variant="h2">Recent expenses</AppText><AppText variant="caption" style={{ color: colors.primary }}>See all</AppText></View>
    <View style={styles.list}>{loading ? <AppText style={{ color: colors.textMuted }}>Loading your expenses…</AppText> : expenses.map(expense => <ExpenseRow key={expense.id} expense={expense} />)}</View>
  </ScrollView><View style={styles.nav}><AppText variant="caption" style={{ color: colors.primary }}>Home</AppText><AppText variant="caption">Groups</AppText><View style={styles.add}><Ionicons name="add" size={26} color={colors.white} /></View><AppText variant="caption">Activity</AppText><AppText variant="caption">Profile</AppText></View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingBottom: 100 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: spacing.xl }, avatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: "#DCE7FF", alignItems: "center", justifyContent: "center" }, summaryCard: { backgroundColor: colors.surface, borderRadius: radius.xl, padding: spacing.xl, borderWidth: 1, borderColor: colors.border }, month: { flexDirection: "row", alignItems: "center", gap: 4 }, balanceRow: { flexDirection: "row", gap: 60, marginTop: spacing.xl, paddingTop: spacing.lg, borderTopWidth: 1, borderTopColor: colors.border }, sectionTitle: { marginTop: spacing.xxl, marginBottom: spacing.lg }, actions: { flexDirection: "row", justifyContent: "space-between" }, sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: spacing.xxxl, marginBottom: spacing.sm }, list: { backgroundColor: colors.surface, borderRadius: radius.lg, paddingHorizontal: spacing.lg, borderWidth: 1, borderColor: colors.border }, nav: { position: "absolute", bottom: 0, left: 0, right: 0, height: 72, backgroundColor: colors.surface, borderTopWidth: 1, borderTopColor: colors.border, flexDirection: "row", justifyContent: "space-around", alignItems: "center" }, add: { width: 52, height: 52, borderRadius: 26, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center", marginTop: -24, borderWidth: 4, borderColor: colors.background } });
